Links to latest numpy version (1.9) instead of 1.7
The numpy download 1.7 causes this error:

>>> import cv2
RuntimeError: module compiled against API version 9 but this version of numpy is
 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import

Getting 1.9 version of numpy fixes it.